[workspace]
resolver = "3"
members = [
    "libs/async_handler",
    "apps/rust-warp-api-rest/backend",
    "apps/rust-warp-api-rest/frontend-api",
    "apps/rust-axum-api-rest/backend",
    "apps/rust-axum-api-rest/frontend-api",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
warp = "0.4"
axum = "0.8"
axum-extra = "0.12"
tokio = "1.53"
tower = "0.5"
tower-http = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
bytes = "1.12"
http-body-util = "0.1"
hyper = "1.11"
hyper-util = "0.1"
reqwest = "0.13"
sqlx = "0.9"
tracing = "0.1"
dotenv = "0.15"
thiserror = "2.0"
anyhow = "1.0"
