### SERVICES ###
services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    ports:
      - "8090:8080"
    environment:
        WIREMOCK_OPTIONS: "--verbose --global-response-templating"
    volumes:
      - ./config:/home/wiremock/mappings/
    networks:
      - wiremock

### NETWORKS ###
networks:
  wiremock:
    name: wiremock
