[package]
name = "rust-warp-rest-api-backend"
version = "1.0.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
