[package]
name = "rust-warp-rest-api-backend"
version = "1.0.0"
edition = "2021"

[dependencies]
warp = "0.4"
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
