[package]
name = "rust-warp-rest-api-frontend-api"
version = "1.0.0"
edition = "2021"

[dependencies]
warp = { workspace = true, features = ["server"] }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
bytes = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true, features = ["full"] }
