[package]
name = "rust-warp-rest-api-frontend-api"
version = "1.0.0"
edition = "2021"

[dependencies]
warp = "0.4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
