name: Build Everything

on:
  push:
    branches:
      - main

jobs:
  build-rust-warp-api-rest:
    name: Build rust-warp-api-rest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Rust ToolChain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build with Cargo - backend
        run: cargo -C ./apps/rust-warp-api-rest/backend/ build
      - name: Build with Cargo - frontend-api
        run: cargo -C ./apps/rust-warp-api-rest/frontend-api/ build
